MvcMovies/Models/ErrorViewModel.cs
namespace MvcMovies.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcMovies/Models/Film.cs
using System.ComponentModel.DataAnnotations;

namespace MvcMovies.Models
{
    public class Film
    {
        public int Id { get; set; }
        public string? Naslov { get; set; }

        [DataType(DataType.Date)]
        public DateTime DatumPocetkaPrikazivanja { get; set; }
        public string? Zanr { get; set; }
        public decimal Ulozeno { get; set; }
    }
}

MvcMovies/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcMovies.Data;
using MvcMovies.Models;

namespace MvcMovies.Controllers
{
    public class FilmsController : Controller
    {
        private readonly MvcMoviesContext _context;

        public FilmsController(MvcMoviesContext context)
        {
            _context = context;
        }

        // GET: Films
        public async Task<IActionResult> Index()
        {
              return View(await _context.Film.ToListAsync());
        }

        // GET: Films/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Film == null)
            {
                return NotFound();
            }

            var film = await _context.Film
                .FirstOrDefaultAsync(m => m.Id == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // GET: Films/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Films/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naslov,DatumPocetkaPrikazivanja,Zanr,Ulozeno")] Film film)
        {
            if (ModelState.IsValid)
            {
                _context.Add(film);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(film);
        }

        // GET: Films/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Film == null)
            {
                return NotFound();
            }

            var film = await _context.Film.FindAsync(id);
            if (film == null)
            {
                return NotFound();
            }
            return View(film);
        }

        // POST: Films/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naslov,DatumPocetkaPrikazivanja,Zanr,Ulozeno")] Film film)
        {
            if (id != film.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(film);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmExists(film.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(film);
        }

        // GET: Films/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Film == null)
            {
                return NotFound();
            }

            var film = await _context.Film
                .FirstOrDefaultAsync(m => m.Id == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // POST: Films/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Film == null)
            {
                return Problem("Entity set 'MvcMoviesContext.Film'  is null.");
            }
            var film = await _context.Film.FindAsync(id);
            if (film != null)
            {
                _context.Film.Remove(film);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmExists(int id)
        {
          return _context.Film.Any(e => e.Id == id);
        }
    }
}

MvcMovies/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcMovies.Models;
using System.Diagnostics;

namespace MvcMovies.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privatnost()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcMovies/Controllers/ZdravoSveteController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace MvcMovie.Controllers
{
    public class ZdravoSveteController : Controller
    {
        // 
        // GET: /ZdravoSvete/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Pozdrav(string ime, int brojPojava = 1)
        {
            ViewData["Poruka"] = "Zdravo " + ime;
            ViewData["BrojPojava"] = brojPojava;

            return View();
        }

        // 
        // GET: /ZdravoSvete/DobroDosli/ 
        public string Dobrodosli()
        {
            return "Ovo je metod za akciju dobrodošlice (DobroDosli)...";
        }

        // 
        // GET: /ZdravoSvete/DobroDosli2/ 
        // Requires using System.Text.Encodings.Web;
        public string Dobrodosli2(string ime, int brojPokusaja = 1)
        {
            return HtmlEncoder.Default.Encode($"Doborodosli, {ime}, broj pokusaja je: {brojPokusaja}");
        }

        // 
        // GET: /ZdravoSvete/DobroDosli3/ 
        // Requires using System.Text.Encodings.Web;
        public string Dobrodosli3(string ime, int ID = 1)
        {
            return HtmlEncoder.Default.Encode($"Dobrodosli {ime}, id je: {ID}");
        }
    }
}

MvcMovies/Views/Films/Create.cshtml
@model MvcMovies.Models.Film

@{
    ViewData["Title"] = "Kreiraj film";
}

<h1>Kreiraj</h1>

<h4>Film</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naslov" class="control-label"></label>
                <input asp-for="Naslov" class="form-control" />
                <span asp-validation-for="Naslov" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumPocetkaPrikazivanja" class="control-label">Početak prikazivanja:</label>
                <input asp-for="DatumPocetkaPrikazivanja" class="form-control" />
                <span asp-validation-for="DatumPocetkaPrikazivanja" class="text-danger"></span>
            </div>
            <div class="form-group">
                Žanr
                <input asp-for="Zanr" class="form-control" />
                <span asp-validation-for="Zanr" class="text-danger"></span>
            </div>
            <div class="form-group">
                Uloženo
                <input asp-for="Ulozeno" class="form-control" />
                <span asp-validation-for="Ulozeno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Kreiraj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Povratak na spisak filmova</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcMovies/Views/Films/Delete.cshtml
@model MvcMovies.Models.Film

@{
    ViewData["Title"] = "Brisanje";
}

<h1>Brisanje</h1>

<h3>Da li ste sigurni da želite da obrišete?</h3>
<div>
    <h4>Film</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naslov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naslov)
        </dd>
        <dt class = "col-sm-2">
            Početak prikazivanja
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatumPocetkaPrikazivanja)
        </dd>
        <dt class = "col-sm-2">
            Žanr
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zanr)
        </dd>
        <dt class = "col-sm-2">
            Uloženo
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ulozeno)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Obriši" class="btn btn-danger" /> |
        <a asp-action="Index">Povratak na spisak filmova</a>
    </form>
</div>

MvcMovies/Views/Films/Details.cshtml
@model MvcMovies.Models.Film

@{
    ViewData["Title"] = "Detalji";
}

<h1>Detalji</h1>

<div>
    <h4>Film</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naslov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naslov)
        </dd>
        <dt class = "col-sm-2">
            Početak prikazivanja
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatumPocetkaPrikazivanja)
        </dd>
        <dt class = "col-sm-2">
            Žanr
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zanr)
        </dd>
        <dt class = "col-sm-2">
            Uloženo
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ulozeno)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Izmeni</a> |
    <a asp-action="Index">Povratak na spisak filmova</a>
</div>

MvcMovies/Views/Films/Edit.cshtml
@model MvcMovies.Models.Film

@{
    ViewData["Title"] = "Izmeni";
}

<h1>Izmeni</h1>

<h4>Film</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Naslov" class="control-label"></label>
                <input asp-for="Naslov" class="form-control" />
                <span asp-validation-for="Naslov" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumPocetkaPrikazivanja" class="control-label">Početak prikazivanja</label>
                <input asp-for="DatumPocetkaPrikazivanja" class="form-control" />
                <span asp-validation-for="DatumPocetkaPrikazivanja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zanr" class="control-label">Žanr</label>
                <input asp-for="Zanr" class="form-control" />
                <span asp-validation-for="Zanr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ulozeno" class="control-label">Uloženo</label>
                <input asp-for="Ulozeno" class="form-control" />
                <span asp-validation-for="Ulozeno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sačuvaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcMovies/Views/Films/Index.cshtml
@model IEnumerable<MvcMovies.Models.Film>

@{
    ViewData["Title"] = "Index";
}

<h1>Filmovi</h1>

<p>
    <a asp-action="Create">Kreiraj</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Naslov)
            </th>
            <th>
                Početak prikazivanja
            </th>
            <th>
                Žanr
            </th>
            <th>
                Uloženo
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naslov)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatumPocetkaPrikazivanja)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zanr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ulozeno)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Izmeni</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalji</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Obriši</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcMovies/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Početna strana";
}

<div class="text-center">
    <h1 class="display-4">Dobrodošli!</h1>
    <p>Mi ćemo <a href="https://docs.microsoft.com/aspnet/core">kreirati web aplikaciju koristeći ASP.NET Core</a>.</p>
</div>

MvcMovies/Views/Home/Privatnost.cshtml
@{
    ViewData["Title"] = "Politika privatnosti";
}
<h1>@ViewData["Title"]</h1>

<p>Ovde će biti detalno ppisana politika privatnosti za veb aplikaciju.</p>

MvcMovies/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Filmovi - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Films" asp-action="Index">Filmovi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Početak</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privatnost">Privatnost</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Filmovi - <a asp-area="" asp-controller="Home" asp-action="Privatnost">Privatnost</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcMovies/Views/ZdravoSvete/Index.cshtml
@*
    Koristna linkl https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Lista filmova";
}

<h2>Zdravo svete</h2>

<p>Pozdrav svetu iz našeg šablona za pogled!</p>

MvcMovies/Views/ZdravoSvete/Pozdrav.cshtml
@*
    Koristna linkl https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Naslov"] = "Lista filmova";
}

<h2>Moja lista filmova</h2>

<ul>
    @for (int i = 0; i < (int)ViewData["BrojPojava"]!; i++)
    {
        <li>@ViewData["Poruka"]</li>
    }
</ul>

<p>Pozdrav svetu iz našeg šablona za pogled!</p>